version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    image: vvvas/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
  frontend:
    image: vvvas/foodgram_frontend
    command: cp -r /app/build/. /app/static/
    volumes:
      - static:/app/static
  gateway:
    depends_on:
      - backend
    image: vvvas/foodgram_gateway
    ports:
      - 9500:80
    volumes:
      - static:/app/static
      - media:/app/media
